# include ./kitty-themes/Brogrammer.conf

font_family FantasqueSansM Nerd Font Mono Bold
font_size 16.0

background #000000
foreground #ffb000
cursor #ffb000
cursor_shape block
cursor_blink_interval 0

selection_foreground #000000
selection_background #ffb000

background_opacity 0.92
dynamic_background_opacity 0
inactive_text_alpha 0.76

window_padding_width 6
enable_audio_bell no

bold_is_bright yes

color0  #000000
color1  #ffb000
color2  #cc8a00
color3  #ffb000
color4  #cc8a00
color5  #ffb000
color6  #cc8a00
color7  #ffcc66
color8  #665000
color9  #ffb000
color10 #cc8a00
color11 #ffb000
color12 #cc8a00
color13 #ffb000
color14 #cc8a00
color15 #fff5cc
